import http from 'http';
import { readFile } from 'fs/promises';
import { extname, join } from 'path';
import { chromium } from 'playwright-core';
const ROOT = '/home/user/Video-Game-1';
const MIME = { '.html':'text/html', '.js':'text/javascript', '.png':'image/png', '.glb':'model/gltf-binary', '.gltf':'model/gltf+json', '.bin':'application/octet-stream' };
const server = http.createServer(async (req,res)=>{ try{ let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/index.html'; const d=await readFile(join(ROOT,p)); res.writeHead(200,{'Content-Type':MIME[extname(p)]||'application/octet-stream'}); res.end(d);}catch{res.writeHead(404);res.end('nf');}});
await new Promise(r=>server.listen(8932,r));
const browser = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', headless:true, args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const page = await browser.newPage({ viewport:{width:844,height:390} });
page.on('console', m=>{ if(m.type()==='error') console.log('CONSOLE:', m.text().slice(0,300)); });
page.on('pageerror', e=>console.log('PAGEERROR:', (e.stack||String(e)).slice(0,600)));
page.on('requestfailed', r=>console.log('REQFAIL:', r.url().slice(-80)));
page.on('response', r=>{ if(r.status()>=400) console.log('HTTP'+r.status()+':', r.url().slice(-90)); });
await page.goto('http://localhost:8932/?debug', { waitUntil:'load' });
await page.waitForTimeout(500);
await page.click('#btn-new');
await page.waitForTimeout(9000);
const err = await page.evaluate(()=>document.querySelector('div[style*="80,0,0"]')?.textContent || '(no overlay)');
console.log('OVERLAY:', err.slice(0,1200));
console.log('g exists:', await page.evaluate(()=>!!window.g), 'title hidden:', await page.evaluate(()=>document.getElementById('title')?.classList?.contains('hidden')));
await browser.close(); server.close();
