class_name PoiSite
extends Node3D
## Root of every story-location scene (scenes/poi/<id>.tscn, generated by tools/blender/poi/build.py).
## The scene is an inherited instance of assets/models/poi/<id>.glb (merged static meshes, one surface per
## library material) plus, generated alongside:
##   Collision/Body_<surface>   StaticBody3D (layer 1 "world") per footstep surface (meta "surface": wood/metal/rock/…)
##   Sockets/<name>             Marker3D gameplay sockets: Loot_*, Log_<log id>, Use_* (Use_Radio, Use_Generator,
##                              Use_Door_Mine, …), Arrive_* (spawn / arrival points), Npc_*, Spot_*
##   Lights_Interior            lights that come on with power / a lit lamp (off by default where noted)
##   Shelter areas (group "shelter"), heat-source slots (group "heat_source", inactive until lit), ReflectionProbes
## Emissive surfaces (window glow, lamp bulbs, screens) follow set_interior_lights().

@export var poi_id: StringName
@export var interior := false               ## a standalone interior (mine tunnels, ice cave), placed below the terrain
@export var interior_lights_on := false
@export var lit_materials: PackedStringArray  ## material names (assets/models/poi/materials/*.tres) that glow when lit

var _lit: Array[ShaderMaterial] = []


func _ready() -> void:
	add_to_group(&"poi")
	add_to_group(&"persistent")
	_collect_lit_materials()
	set_interior_lights(interior_lights_on)


## Turns the interior light group and every emissive surface of this site on/off (power restored, lamp lit).
func set_interior_lights(on: bool) -> void:
	interior_lights_on = on
	var g := get_node_or_null(^"Lights_Interior") as Node3D
	if g:
		g.visible = on
	for m in _lit:
		m.set_shader_parameter(&"lit", 1.0 if on else 0.0)


func get_socket(socket_name: String) -> Marker3D:
	return get_node_or_null(NodePath("Sockets/" + socket_name)) as Marker3D


## All sockets whose name starts with `prefix` ("Loot_", "Log_", "Use_", "Arrive_"…), in scene order.
func get_sockets(prefix: String = "") -> Array[Marker3D]:
	var out: Array[Marker3D] = []
	var s := get_node_or_null(^"Sockets")
	if s == null:
		return out
	for c in s.get_children():
		if c is Marker3D and String(c.name).begins_with(prefix):
			out.append(c as Marker3D)
	return out


func get_save_key() -> String:
	return "poi_" + String(poi_id) + ("_interior" if interior else "")


func save_state() -> Dictionary:
	return {"lights": interior_lights_on}


func load_state(data: Dictionary) -> void:
	set_interior_lights(bool(data.get("lights", interior_lights_on)))


# Each site gets its own copies of the emissive materials so switching one site doesn't light another.
func _collect_lit_materials() -> void:
	if lit_materials.is_empty():
		return
	var dup := {}
	for mi in find_children("*", "MeshInstance3D", true, false):
		var m := mi as MeshInstance3D
		if m.mesh == null:
			continue
		for i in m.mesh.get_surface_count():
			var mat := m.mesh.surface_get_material(i) as ShaderMaterial
			if mat == null:
				continue
			var nm := mat.resource_path.get_file().get_basename()
			if not lit_materials.has(nm):
				continue
			if not dup.has(nm):
				var d := mat.duplicate() as ShaderMaterial
				dup[nm] = d
				_lit.append(d)
			m.set_surface_override_material(i, dup[nm])
