extends Node
## Global signal bus. No logic lives here — see CONTRACT.md §3.

@warning_ignore_start("unused_signal")
signal notification(text: String, kind: StringName)
signal interaction_prompt(text: String, hold_time: float)
signal interaction_progress(t: float)
signal item_picked_up(id: StringName, count: int)
signal item_dropped(id: StringName, count: int)
signal item_crafted(id: StringName, count: int)
signal item_consumed(id: StringName)
signal inventory_changed()
signal equipment_changed(slot: StringName, id: StringName)
signal active_item_changed(id: StringName)
signal blueprint_unlocked(id: StringName)
signal scan_completed(target_id: StringName)
signal player_damaged(amount: float, type: StringName, source: Node)
signal player_died(cause: StringName)
signal player_respawned()
signal status_effect_changed(id: StringName, active: bool)
signal footstep(surface: StringName, position: Vector3, intensity: float)
signal player_landed(fall_speed: float, surface: StringName)
signal noise_emitted(position: Vector3, radius: float, source: Node)
signal poi_discovered(poi_id: StringName)
signal zone_entered(zone_id: StringName)
signal objective_added(id: StringName, text: String)
signal objective_completed(id: StringName)
signal log_found(log_id: StringName)
signal radio_message(message_id: StringName)
signal subtitle(speaker: String, text: String, duration: float)
signal weather_changed(weather: StringName)
signal hour_passed(hour: int)
signal day_started(day: int)
signal structure_built(buildable_id: StringName, node: Node3D)
signal structure_destroyed(buildable_id: StringName, node: Node3D)
signal tree_felled(position: Vector3, species: StringName)
signal resource_harvested(id: StringName, position: Vector3)
signal animal_killed(species: StringName, position: Vector3)
signal game_started(is_new: bool)
signal game_saved(slot: int)
signal game_loaded(slot: int)
signal settings_changed()
signal ui_screen_opened(screen: StringName)
signal ui_screen_closed(screen: StringName)
signal cinematic_started(id: StringName)
signal cinematic_ended(id: StringName)
signal sleep_started(hours: float)
signal sleep_ended()
@warning_ignore_restore("unused_signal")
