extends Node
## TerrainData — the mountain as data: 2049² heightfield (1.5 m), surface masks, water, POIs, trails, and the
## GPU textures + global shader parameters every terrain-aware shader samples. CONTRACT.md §3.
## Generated by tools/terrain/gen_terrain.py (see tools/README.md); world layout in data/world_layout.json.
##
## Global shader parameters published here (declared in project.godot):
##   terrain_height_tex (RF, 2049², sample with texelFetch / manual bilinear), terrain_normal_tex (RGB world
##   normal * 0.5 + 0.5, A sky visibility), terrain_mask_tex (R snow, G rock, B grass, A forest; 1025²),
##   terrain_mask2_tex (R scree, G gravel, B glacier ice, A wetness), terrain_params (vec4: origin x, origin z,
##   world size, cell), terrain_shadow_tex / terrain_shadow_params (set by the terrain renderer's sun-shadow pass).
##
## API beyond the contract (additive): get_height_extended(), get_masks2(), get_water_depth(), get_trail_at(),
## get_trails(), get_rivers(), get_lakes(), is_hole(), mid_heights/far_heights + textures, signal data_loaded.

signal data_loaded()

const SIZE := 2049
const CELL := 1.5
const WORLD_SIZE := 3072.0
const HALF := 1536.0
const MASK_SIZE := 1025
const MASK_CELL := 3.0
const MID_SIZE := 1025
const MID_CELL := 6.0
const MID_HALF := 3072.0
const FAR_SIZE := 1025
const FAR_CELL := 48.0
const FAR_HALF := 24576.0

const DIR := "res://assets/terrain/"
const LAYOUT_PATH := "res://data/world_layout.json"
const WATER_GRID := 96                      # spatial hash for water / trail lookups (32 m cells)
const WATER_CELL := WORLD_SIZE / WATER_GRID

var heights: PackedFloat32Array
var height_texture: Texture2D
var normal_texture: Texture2D
var mask_texture: Texture2D
var mask2_texture: Texture2D
var detail_texture: Texture2D
var mid_heights: PackedFloat32Array
var far_heights: PackedFloat32Array
var mid_texture: Texture2D
var far_texture: Texture2D
var layout: Dictionary = {}
var min_height := 0.0
var max_height := 0.0

var masks: PackedByteArray               # MASK_SIZE² RGBA8
var masks2: PackedByteArray
var _loaded := false
var _pois: Array[Dictionary] = []
var _poi_index: Dictionary = {}
# water/trail features: arrays of Dictionaries + spatial hash cell -> PackedInt32Array of feature indices
var _water_features: Array[Dictionary] = []
var _water_grid: Array = []
var _trail_segs: PackedFloat32Array = PackedFloat32Array()   # x0,z0,x1,z1,half_width per segment
var _trail_grid: Array = []
var _holes: Array[Dictionary] = []


func _ready() -> void:
	load_data()


func load_data() -> bool:
	if _loaded:
		return true
	var t0 := Time.get_ticks_usec()
	var hb := FileAccess.get_file_as_bytes(DIR + "height.f32")
	if hb.size() != SIZE * SIZE * 4:
		push_warning("TerrainData: height.f32 missing or wrong size (%d bytes) — flat fallback" % hb.size())
		_make_flat()
		return false
	heights = hb.to_float32_array()
	min_height = INF
	max_height = -INF
	# min/max over a coarse stride is plenty (exact values also in the layout)
	for j in range(0, SIZE, 8):
		var row := j * SIZE
		for i in range(0, SIZE, 8):
			var v: float = heights[row + i]
			min_height = minf(min_height, v)
			max_height = maxf(max_height, v)
	masks = FileAccess.get_file_as_bytes(DIR + "masks.bin")
	masks2 = FileAccess.get_file_as_bytes(DIR + "masks2.bin")
	if masks.size() != MASK_SIZE * MASK_SIZE * 4:
		masks = PackedByteArray()
		masks.resize(MASK_SIZE * MASK_SIZE * 4)
	if masks2.size() != MASK_SIZE * MASK_SIZE * 4:
		masks2 = PackedByteArray()
		masks2.resize(MASK_SIZE * MASK_SIZE * 4)
	var mb := FileAccess.get_file_as_bytes(DIR + "mid.f32")
	if mb.size() == MID_SIZE * MID_SIZE * 4:
		mid_heights = mb.to_float32_array()
	var fb := FileAccess.get_file_as_bytes(DIR + "far.f32")
	if fb.size() == FAR_SIZE * FAR_SIZE * 4:
		far_heights = fb.to_float32_array()
	_load_layout()
	if layout.has("map"):
		min_height = float(layout["map"].get("min_height", min_height))
		max_height = float(layout["map"].get("max_height", max_height))
	_build_textures(hb, mb, fb)
	_loaded = true
	print("[TerrainData] loaded %d² heightfield (%.0f..%.0f m) in %.1f ms" % [SIZE, min_height, max_height,
		(Time.get_ticks_usec() - t0) / 1000.0])
	data_loaded.emit()
	return true


func _make_flat() -> void:
	heights = PackedFloat32Array()
	heights.resize(SIZE * SIZE)
	heights.fill(1450.0)
	min_height = 1450.0
	max_height = 1450.0
	masks = PackedByteArray()
	masks.resize(MASK_SIZE * MASK_SIZE * 4)
	masks2 = PackedByteArray()
	masks2.resize(MASK_SIZE * MASK_SIZE * 4)
	_load_layout()


func _build_textures(hb: PackedByteArray, mb: PackedByteArray, fb: PackedByteArray) -> void:
	var img := Image.create_from_data(SIZE, SIZE, false, Image.FORMAT_RF, hb)
	height_texture = ImageTexture.create_from_image(img)
	if mb.size() == MID_SIZE * MID_SIZE * 4:
		mid_texture = ImageTexture.create_from_image(Image.create_from_data(MID_SIZE, MID_SIZE, false, Image.FORMAT_RF, mb))
	if fb.size() == FAR_SIZE * FAR_SIZE * 4:
		far_texture = ImageTexture.create_from_image(Image.create_from_data(FAR_SIZE, FAR_SIZE, false, Image.FORMAT_RF, fb))
	var mi := Image.create_from_data(MASK_SIZE, MASK_SIZE, false, Image.FORMAT_RGBA8, masks)
	mi.generate_mipmaps()
	mask_texture = ImageTexture.create_from_image(mi)
	var mi2 := Image.create_from_data(MASK_SIZE, MASK_SIZE, false, Image.FORMAT_RGBA8, masks2)
	mi2.generate_mipmaps()
	mask2_texture = ImageTexture.create_from_image(mi2)
	if ResourceLoader.exists(DIR + "normal.png"):
		normal_texture = load(DIR + "normal.png")
	if ResourceLoader.exists(DIR + "detail.png"):
		detail_texture = load(DIR + "detail.png")
	var rs := RenderingServer
	rs.global_shader_parameter_set(&"terrain_height_tex", height_texture)
	if normal_texture:
		rs.global_shader_parameter_set(&"terrain_normal_tex", normal_texture)
	rs.global_shader_parameter_set(&"terrain_mask_tex", mask_texture)
	rs.global_shader_parameter_set(&"terrain_mask2_tex", mask2_texture)
	rs.global_shader_parameter_set(&"terrain_params", Vector4(-HALF, -HALF, WORLD_SIZE, CELL))


func _load_layout() -> void:
	layout = {}
	if FileAccess.file_exists(LAYOUT_PATH):
		var v: Variant = JSON.parse_string(FileAccess.get_file_as_string(LAYOUT_PATH))
		if v is Dictionary:
			layout = v
	_pois.clear()
	_poi_index.clear()
	for p in layout.get("pois", []):
		var d: Dictionary = (p as Dictionary).duplicate(true)
		d["id"] = StringName(str(p.get("id", "")))
		d["position"] = Vector3(float(p.get("x", 0.0)), float(p.get("y", 0.0)), float(p.get("z", 0.0)))
		_poi_index[d["id"]] = _pois.size()
		_pois.append(d)
	_build_water_index()
	_build_trail_index()
	_holes.clear()
	for hd in layout.get("holes", []):
		_holes.append(hd)


# =========================================================================================== queries
func is_loaded() -> bool:
	return _loaded


func in_bounds(x: float, z: float, margin := 0.0) -> bool:
	return absf(x) <= HALF - margin and absf(z) <= HALF - margin


func get_height(x: float, z: float) -> float:
	if heights.is_empty():
		return 0.0
	var fx := clampf((x + HALF) / CELL, 0.0, SIZE - 1.0)
	var fz := clampf((z + HALF) / CELL, 0.0, SIZE - 1.0)
	var i := mini(int(fx), SIZE - 2)
	var j := mini(int(fz), SIZE - 2)
	var u := fx - i
	var v := fz - j
	var k := j * SIZE + i
	var h00: float = heights[k]
	var h10: float = heights[k + 1]
	var h01: float = heights[k + SIZE]
	var h11: float = heights[k + SIZE + 1]
	return lerpf(lerpf(h00, h10, u), lerpf(h01, h11, u), v)


## Height anywhere: the map, then the surrounding MID band (6 m) and FAR range (48 m).
func get_height_extended(x: float, z: float) -> float:
	if absf(x) <= HALF and absf(z) <= HALF:
		return get_height(x, z)
	if absf(x) <= MID_HALF and absf(z) <= MID_HALF and not mid_heights.is_empty():
		return _bilinear(mid_heights, MID_SIZE, MID_HALF, MID_CELL, x, z)
	if not far_heights.is_empty():
		return _bilinear(far_heights, FAR_SIZE, FAR_HALF, FAR_CELL, x, z)
	return get_height(x, z)


func _bilinear(a: PackedFloat32Array, n: int, half: float, cell: float, x: float, z: float) -> float:
	var fx := clampf((x + half) / cell, 0.0, n - 1.0)
	var fz := clampf((z + half) / cell, 0.0, n - 1.0)
	var i := mini(int(fx), n - 2)
	var j := mini(int(fz), n - 2)
	var u := fx - i
	var v := fz - j
	var k := j * n + i
	return lerpf(lerpf(a[k], a[k + 1], u), lerpf(a[k + n], a[k + n + 1], u), v)


func get_normal(x: float, z: float) -> Vector3:
	var e := CELL
	var hl := get_height(x - e, z)
	var hr := get_height(x + e, z)
	var hd := get_height(x, z - e)
	var hu := get_height(x, z + e)
	return Vector3(hl - hr, 2.0 * e, hd - hu).normalized()


func get_slope_deg(x: float, z: float) -> float:
	return rad_to_deg(acos(clampf(get_normal(x, z).y, -1.0, 1.0)))


func _mask_sample(buf: PackedByteArray, x: float, z: float) -> Color:
	if buf.is_empty():
		return Color(0, 0, 0, 0)
	var fx := clampf((x + HALF) / MASK_CELL, 0.0, MASK_SIZE - 1.0)
	var fz := clampf((z + HALF) / MASK_CELL, 0.0, MASK_SIZE - 1.0)
	var i := mini(int(fx), MASK_SIZE - 2)
	var j := mini(int(fz), MASK_SIZE - 2)
	var u := fx - i
	var v := fz - j
	var k := (j * MASK_SIZE + i) * 4
	var k2 := k + MASK_SIZE * 4
	var out := Color()
	for c in 4:
		var a := lerpf(buf[k + c], buf[k + 4 + c], u)
		var b := lerpf(buf[k2 + c], buf[k2 + 4 + c], u)
		out[c] = lerpf(a, b, v) / 255.0
	return out


## R snow, G rock, B alpine grass / meadow, A forest density.
func get_masks(x: float, z: float) -> Color:
	return _mask_sample(masks, x, z)


## R scree/talus/moraine, G gravel (river bars, outwash), B glacier ice, A wetness.
func get_masks2(x: float, z: float) -> Color:
	return _mask_sample(masks2, x, z)


func get_surface(x: float, z: float) -> StringName:
	var m := get_masks(x, z)
	var m2 := get_masks2(x, z)
	var y := get_height(x, z)
	var wl := get_water_level(x, z)
	if wl > y + 0.05:
		return &"gravel"
	if m2.b > 0.5:
		return &"snow" if m.r > 0.82 else &"ice"
	if get_trail_at(x, z) and m.r < 0.6:
		return &"dirt" if y < 2300.0 else &"gravel"
	if m.r > 0.55:
		return &"snow"
	var slope := get_slope_deg(x, z)
	if m.g > 0.55 or slope > 52.0:
		return &"rock"
	if m2.r > 0.5:
		return &"scree"
	if m2.g > 0.5:
		return &"gravel"
	if m.a > 0.45:
		return &"forest"
	if m.b > 0.3:
		return &"grass"
	if m.g > 0.3:
		return &"rock"
	if m2.r > 0.25:
		return &"scree"
	return &"dirt" if y < 2200.0 else &"scree"


func get_biome(x: float, z: float) -> StringName:
	if in_bounds(x, z) and get_masks2(x, z).b > 0.5:
		return &"glacier"
	var y := get_height_extended(x, z)
	if y < 1550.0:
		return &"valley"
	if y < 2100.0:
		return &"forest"
	if y < 2450.0:
		return &"subalpine"
	if y < 3150.0:
		return &"alpine"
	return &"summit"


# =========================================================================================== water
func _build_water_index() -> void:
	_water_features.clear()
	_water_grid.clear()
	_water_grid.resize(WATER_GRID * WATER_GRID)
	for k in _water_grid.size():
		_water_grid[k] = PackedInt32Array()
	for lk in layout.get("lakes", []):
		var f := {"type": 0, "level": float(lk.get("level", 0.0)), "x": float(lk.get("x", 0.0)),
			"z": float(lk.get("z", 0.0)), "r": float(lk.get("radius", 0.0))}
		var poly := PackedVector2Array()
		for p in lk.get("polygon", []):
			poly.append(Vector2(float(p[0]), float(p[1])))
		f["poly"] = poly
		var bb := Rect2(f["x"] - f["r"], f["z"] - f["r"], f["r"] * 2.0, f["r"] * 2.0)
		if poly.size() >= 3:
			bb = Rect2(poly[0], Vector2.ZERO)
			for p2 in poly:
				bb = bb.expand(p2)
		_add_water(f, bb)
	for rv in layout.get("rivers", []):
		var pts: Array = rv.get("points", [])
		for s in range(pts.size() - 1):
			var a: Array = pts[s]
			var b: Array = pts[s + 1]
			var w := maxf(float(a[3]), float(b[3])) * 0.5 + 0.5
			var f2 := {"type": 1, "ax": float(a[0]), "ay": float(a[1]), "az": float(a[2]), "bx": float(b[0]),
				"by": float(b[1]), "bz": float(b[2]), "wa": float(a[3]) * 0.5 + 0.5, "wb": float(b[3]) * 0.5 + 0.5}
			var bb2 := Rect2(Vector2(f2["ax"], f2["az"]), Vector2.ZERO).expand(Vector2(f2["bx"], f2["bz"])).grow(w)
			_add_water(f2, bb2)


func _add_water(f: Dictionary, bb: Rect2) -> void:
	var idx := _water_features.size()
	_water_features.append(f)
	var c0 := _cell_of(bb.position.x, bb.position.y)
	var c1 := _cell_of(bb.end.x, bb.end.y)
	for cj in range(c0.y, c1.y + 1):
		for ci in range(c0.x, c1.x + 1):
			var arr: PackedInt32Array = _water_grid[cj * WATER_GRID + ci]
			arr.append(idx)
			_water_grid[cj * WATER_GRID + ci] = arr


func _cell_of(x: float, z: float) -> Vector2i:
	return Vector2i(clampi(int((x + HALF) / WATER_CELL), 0, WATER_GRID - 1),
		clampi(int((z + HALF) / WATER_CELL), 0, WATER_GRID - 1))


## Surface Y of the lake / river / tarn at (x, z), or -INF if there is no water there.
func get_water_level(x: float, z: float) -> float:
	if _water_grid.is_empty() or not in_bounds(x, z):
		return -INF
	var c := _cell_of(x, z)
	var cand: PackedInt32Array = _water_grid[c.y * WATER_GRID + c.x]
	var best := -INF
	var p := Vector2(x, z)
	for idx in cand:
		var f: Dictionary = _water_features[idx]
		if f["type"] == 0:
			var poly: PackedVector2Array = f["poly"]
			var inside := false
			if poly.size() >= 3:
				inside = Geometry2D.is_point_in_polygon(p, poly)
			else:
				inside = p.distance_to(Vector2(f["x"], f["z"])) <= float(f["r"])
			if inside:
				best = maxf(best, float(f["level"]))
		else:
			var a := Vector2(f["ax"], f["az"])
			var b := Vector2(f["bx"], f["bz"])
			var ab := b - a
			var l2 := ab.length_squared()
			var t := 0.0 if l2 < 1e-6 else clampf((p - a).dot(ab) / l2, 0.0, 1.0)
			var q := a + ab * t
			var half_w := lerpf(float(f["wa"]), float(f["wb"]), t)
			if p.distance_squared_to(q) <= half_w * half_w:
				best = maxf(best, lerpf(float(f["ay"]), float(f["by"]), t))
	return best


func is_in_water(p: Vector3) -> bool:
	return p.y < get_water_level(p.x, p.z)


## Water depth at (x, z) (surface minus bed), 0 when dry.
func get_water_depth(x: float, z: float) -> float:
	var wl := get_water_level(x, z)
	if wl == -INF:
		return 0.0
	return maxf(wl - get_height(x, z), 0.0)


# =========================================================================================== trails
func _build_trail_index() -> void:
	_trail_segs = PackedFloat32Array()
	_trail_grid.clear()
	_trail_grid.resize(WATER_GRID * WATER_GRID)
	for k in _trail_grid.size():
		_trail_grid[k] = PackedInt32Array()
	for tr in layout.get("trails", []):
		var pts: Array = tr.get("points", [])
		var hw := float(tr.get("width", 1.2)) * 0.5 + 0.3
		for s in range(pts.size() - 1):
			var a: Array = pts[s]
			var b: Array = pts[s + 1]
			var si := _trail_segs.size() / 5
			_trail_segs.append_array(PackedFloat32Array([float(a[0]), float(a[2]), float(b[0]), float(b[2]), hw]))
			var bb := Rect2(Vector2(a[0], a[2]), Vector2.ZERO).expand(Vector2(b[0], b[2])).grow(hw)
			var c0 := _cell_of(bb.position.x, bb.position.y)
			var c1 := _cell_of(bb.end.x, bb.end.y)
			for cj in range(c0.y, c1.y + 1):
				for ci in range(c0.x, c1.x + 1):
					var arr: PackedInt32Array = _trail_grid[cj * WATER_GRID + ci]
					arr.append(si)
					_trail_grid[cj * WATER_GRID + ci] = arr


## True on a trail tread (valley trail, mine road, routes).
func get_trail_at(x: float, z: float) -> bool:
	if _trail_grid.is_empty() or not in_bounds(x, z):
		return false
	var c := _cell_of(x, z)
	var cand: PackedInt32Array = _trail_grid[c.y * WATER_GRID + c.x]
	var p := Vector2(x, z)
	for si in cand:
		var o := si * 5
		var a := Vector2(_trail_segs[o], _trail_segs[o + 1])
		var b := Vector2(_trail_segs[o + 2], _trail_segs[o + 3])
		var q := Geometry2D.get_closest_point_to_segment(p, a, b)
		if p.distance_squared_to(q) <= _trail_segs[o + 4] * _trail_segs[o + 4]:
			return true
	return false


func get_trails() -> Array:
	return layout.get("trails", [])


func get_rivers() -> Array:
	return layout.get("rivers", [])


func get_lakes() -> Array:
	return layout.get("lakes", [])


## Inside a cut-out (mine adit portal, ice cave mouth) where the heightfield has no surface.
func is_hole(x: float, z: float) -> bool:
	for hd in _holes:
		var dx := x - float(hd.get("x", 0.0))
		var dz := z - float(hd.get("z", 0.0))
		var r := float(hd.get("radius", 0.0))
		if dx * dx + dz * dz <= r * r:
			return true
	return false


# =========================================================================================== POIs
func get_poi(id: StringName) -> Dictionary:
	var k: Variant = _poi_index.get(id)
	if k == null:
		return {}
	return _pois[int(k)]


func all_pois() -> Array[Dictionary]:
	return _pois


# =========================================================================================== raycast
## Ray vs heightfield. Returns {hit: bool, position: Vector3, normal: Vector3, distance: float}.
func raycast(from: Vector3, dir: Vector3, max_dist: float) -> Dictionary:
	if heights.is_empty() or dir.length_squared() < 1e-12:
		return {"hit": false}
	var d := dir.normalized()
	var t := 0.0
	var prev_t := 0.0
	var prev_above := from.y - get_height(from.x, from.z)
	if prev_above < 0.0:
		return {"hit": true, "position": from, "normal": get_normal(from.x, from.z), "distance": 0.0}
	while t < max_dist:
		# step by the clearance (can't hit anything closer than the height margin on steep 80° ground)
		var step := clampf(prev_above * 0.35, CELL * 0.5, 30.0)
		t = minf(t + step, max_dist)
		var p := from + d * t
		var above := p.y - get_height(p.x, p.z)
		if above <= 0.0:
			var a := prev_t
			var b := t
			for _i in 20:
				var m := (a + b) * 0.5
				var pm := from + d * m
				if pm.y - get_height(pm.x, pm.z) > 0.0:
					a = m
				else:
					b = m
			var hp := from + d * b
			hp.y = get_height(hp.x, hp.z)
			return {"hit": true, "position": hp, "normal": get_normal(hp.x, hp.z), "distance": b}
		prev_t = t
		prev_above = above
		if t >= max_dist:
			break
	return {"hit": false}
